// Generated by tools/model_asset_storage.py; exact original JSON bytes.
concat!(
    include_str!("shared.geometry.json.chunks/000.txt"),
    include_str!("shared.geometry.json.chunks/001.txt"),
    include_str!("shared.geometry.json.chunks/002.txt"),
    include_str!("shared.geometry.json.chunks/003.txt"),
    include_str!("shared.geometry.json.chunks/004.txt"),
)
