export const createChannelState = () => ({
    tempo: 0x0100,
    note_length: 1,
    duration_modifier: 0,
    default_length: null,
    volume_envelope: null,
    octave: 4,
    duty_cycle: 2,
    duty_cycle_loop_enabled: false,
    duty_cycle_pattern_byte: null,
    transpose_octaves: 0,
    transpose_pitches: 0,
    wave_instrument: null,
    wave_volume: 0,
    instrument_id: null,
    instrument_pitch_offset: 0,
    vibrato_delay: 0,
    vibrato_delay_count: 0,
    vibrato_extent: 0,
    vibrato_rate: 0,
    vibrato_rate_counter: 0,
    vibrato_extent_up: 0,
    vibrato_extent_down: 0,
    vibrato_direction_up: false,
    vibrato_latched_reg: 0,
    pitch_offset: 0,
    current_pan: [true, true],
    pitch_sweep_value: 0,
    pitch_sweep_enabled: false,
    pitch_sweep_shadow: 0,
    pulse1_active: true,
    pitch_slide_target: null,
    pitch_slide_frames: 0,
    noise_sampling_enabled: false,
    noise_lfsr: 0x7fff,
    noise_accumulator: 0.0,
});
