[package]
name = "crystal-net"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bincode.workspace = true
crystal-core = { path = "../crystal-core" }
ewebsock = { version = "0.8", features = ["tls"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid = { version = "1", features = ["js", "serde", "v4"] }

[dev-dependencies]
crystal-core = { path = "../crystal-core", features = ["test-fixtures"] }
serde_json.workspace = true
