// Source identities and sparse masks only; no source pixels or game content.
const MAPS: &[&str] = &[
    "CeladonPokecenter2FBeta",
    "CeruleanPokecenter2FBeta",
    "CinnabarPokecenter2FBeta",
    "FuchsiaPokecenter2FBeta",
    "LavenderPokecenter2FBeta",
    "PewterPokecenter2FBeta",
    "Pokecenter2F",
    "Route10Pokecenter2FBeta",
    "SaffronPokecenter2FBeta",
    "VermilionPokecenter2FBeta",
    "ViridianPokecenter2FBeta",
];
const NETWORKS: &[Network] = &[
    Network {
        finish: Finish::Partition,
        anchor: [5, 0],
        width: 4,
        height: 9,
        fingerprint: 0x672a88e9b1c87a97,
        rows: &[6, 6, 6, 6, 6, 6, 6, 6, 0],
        shells: &[[1, 0, 2, 8]],
        record_sign: false,
    },
    Network {
        finish: Finish::Partition,
        anchor: [13, 0],
        width: 4,
        height: 9,
        fingerprint: 0x1699ed2747d5e75f,
        rows: &[6, 6, 6, 6, 6, 6, 6, 6, 0],
        shells: &[[1, 0, 2, 8]],
        record_sign: true,
    },
    Network {
        finish: Finish::Partition,
        anchor: [21, 0],
        width: 11,
        height: 9,
        fingerprint: 0x329df3471d9275b2,
        rows: &[1950, 1950, 1950, 1950, 1950, 1950, 1542, 1542, 0],
        shells: &[[1, 0, 2, 8], [3, 0, 2, 6], [7, 0, 2, 6], [9, 0, 2, 8]],
        record_sign: false,
    },
];

// The capsule guard includes the separate source doorway and its attendant
// approach. The floor guards include the counters above each floor strip.
// All rectangles use exact source-map coordinates, independent of viewport.
const ROOM_FINISH: &[Network] = &[
    Network {
        finish: Finish::TimeCapsule,
        anchor: [25, 0],
        width: 4,
        height: 7,
        fingerprint: 0x69b5f270107140ee,
        rows: &[6, 6, 6, 6, 0, 0, 0],
        shells: &[[1, 0, 2, 4]],
        record_sign: false,
    },
    Network {
        finish: Finish::CeramicFloor,
        anchor: [0, 2],
        width: 8,
        height: 6,
        fingerprint: 0x268b97bef023e886,
        rows: &[63, 0, 0, 0, 63, 0],
        shells: &[],
        record_sign: false,
    },
    Network {
        finish: Finish::CeramicFloor,
        anchor: [8, 2],
        width: 8,
        height: 6,
        fingerprint: 0x71baf867e0488199,
        rows: &[15, 0, 0, 0, 51, 0],
        shells: &[],
        record_sign: false,
    },
    Network {
        finish: Finish::CeramicFloor,
        anchor: [16, 2],
        width: 8,
        height: 6,
        fingerprint: 0x5525d5c0fe296e79,
        rows: &[15, 0, 0, 0, 51, 0],
        shells: &[],
        record_sign: false,
    },
    Network {
        finish: Finish::CeramicFloor,
        anchor: [24, 2],
        width: 8,
        height: 6,
        fingerprint: 0xd53d6db59fb211e3,
        rows: &[0, 0, 0, 0, 63, 0],
        shells: &[],
        record_sign: false,
    },
];
