// Exact source identities and sparse masks only; no game artwork or events.
const NETWORKS: &[Network] = &[
    Network {
        floor: 1,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0x09863dedf710c6d2,
        rows: &[0x3fffffcf, 0x3fffffcf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 8,
                y: 0,
                width: 20,
                depth: 2,
                asset: Asset::Window10,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 2,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0x76635a8372ce496f,
        rows: &[0x3cf000cf, 0x3cf000cf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 20,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 26,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Window1,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 3,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0xcdd07b16c8060866,
        rows: &[0x3cffffcf, 0x3cffffcf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 8,
                y: 0,
                width: 16,
                depth: 2,
                asset: Asset::Window8,
            },
            Part {
                x: 26,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Window1,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 4,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0x091cd3b09f15ca42,
        rows: &[0x3cf00fcf, 0x3cf00fcf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 8,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 20,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 26,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Window1,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 5,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0x68f01e0e9f131692,
        rows: &[0x3cffffcf, 0x3cffffcf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 8,
                y: 0,
                width: 16,
                depth: 2,
                asset: Asset::Window8,
            },
            Part {
                x: 26,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Window1,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 6,
        anchor: [0, 0],
        width: 32,
        height: 4,
        fingerprint: 0xef4026f30ad34252,
        rows: &[0x3300ffcf, 0x3300ffcf, 0, 0],
        label: "mart/department_store_wall",
        parts: &[
            Part {
                x: 0,
                y: 0,
                width: 4,
                depth: 2,
                asset: Asset::Window2,
            },
            Part {
                x: 6,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::LiftSide,
            },
            Part {
                x: 8,
                y: 0,
                width: 8,
                depth: 2,
                asset: Asset::Window4,
            },
            Part {
                x: 24,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Window1,
            },
            Part {
                x: 28,
                y: 0,
                width: 2,
                depth: 2,
                asset: Asset::Directory,
            },
        ],
    },
    Network {
        floor: 5,
        anchor: [12, 8],
        width: 8,
        height: 8,
        fingerprint: 0xf9782caec2a25df4,
        rows: &[255, 255, 195, 195, 255, 255, 255, 255],
        label: "mart/department_store_closed_u",
        parts: &[Part {
            x: 0,
            y: 0,
            width: 8,
            depth: 8,
            asset: Asset::ClosedU,
        }],
    },
];
