// Exact complete-drawing identities and sparse ownership, not source artwork.
const RULES: &[Rule] = &[
    // Complete block $27 northeast round stool, including its source legs.
    Rule {
        map: "RadioTower3F",
        tileset: "radio_tower",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0xfdc734bcf7a1788d,
        rows: &[0x3, 0x3],
        kind: Kind::RoundStool,
        ground: Ground::Radio,
    },
    // Complete block $27 northeast round stool, including its source legs.
    Rule {
        map: "RadioTower4F",
        tileset: "radio_tower",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0xfdc734bcf7a1788d,
        rows: &[0x3, 0x3],
        kind: Kind::RoundStool,
        ground: Ground::Radio,
    },
    // Complete block $27 northeast round stool, including its source legs.
    Rule {
        map: "RadioTower5F",
        tileset: "radio_tower",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0xfdc734bcf7a1788d,
        rows: &[0x3, 0x3],
        kind: Kind::RoundStool,
        ground: Ground::Radio,
    },
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x01b563ed52651d2e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x810a13abcf08c12e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x01b563ed52651d2e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Diamond,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x810a13abcf08c12e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Diamond,
    },
    Rule {
        map: "RuinsOfAlphResearchCenter",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x01b563ed52651d2e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "RuinsOfAlphResearchCenter",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x810a13abcf08c12e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x01b563ed52651d2e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x810a13abcf08c12e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "TrainerHouseB1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x01b563ed52651d2e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "TrainerHouseB1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 4,
        fingerprint: 0x810a13abcf08c12e,
        rows: &[0x3, 0x3, 0x3, 0x3],
        kind: Kind::InstrumentBank,
        ground: Ground::Checker,
    },
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 3,
        fingerprint: 0x1ac974d5e482fa85,
        rows: &[0xf, 0xf, 0xf],
        kind: Kind::Workbench,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 3,
        fingerprint: 0x89a2052809963d05,
        rows: &[0xf, 0xf, 0xf],
        kind: Kind::Workbench,
        ground: Ground::Checker,
    },
    Rule {
        map: "RuinsOfAlphResearchCenter",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 3,
        fingerprint: 0x1ac974d5e482fa85,
        rows: &[0xf, 0xf, 0xf],
        kind: Kind::Workbench,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 3,
        fingerprint: 0x89a2052809963d05,
        rows: &[0xf, 0xf, 0xf],
        kind: Kind::Workbench,
        ground: Ground::Checker,
    },
    Rule {
        map: "RadioTower3F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 2,
        fingerprint: 0x23c8018bce86d4db,
        rows: &[0xf, 0xf],
        kind: Kind::PhoneDesk,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower4F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 2,
        fingerprint: 0x23c8018bce86d4db,
        rows: &[0xf, 0xf],
        kind: Kind::PhoneDesk,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower5F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 2,
        fingerprint: 0x23c8018bce86d4db,
        rows: &[0xf, 0xf],
        kind: Kind::PhoneDesk,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower3F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x68006e0b75c6f068,
        rows: &[0xf, 0xf, 0x0, 0x0],
        kind: Kind::MemoDesk,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower3F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x68006e0b75c6f068,
        rows: &[0x0, 0x0, 0x3, 0x3],
        kind: Kind::Stool,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower1F",
        tileset: "radio_tower",
        anchor: Some([8, 10]),
        width: 20,
        height: 6,
        fingerprint: 0xadfd3b2d881430a3,
        rows: &[0xfffff, 0xfffff, 0xc0c03, 0xc0003, 0xc0003, 0xc0003],
        kind: Kind::ReceptionU,
        ground: Ground::Radio,
    },
    Rule {
        map: "LavRadioTower1F",
        tileset: "radio_tower",
        anchor: Some([8, 10]),
        width: 8,
        height: 6,
        fingerprint: 0xf411edb1571925ab,
        rows: &[0xff, 0xff, 0x3, 0x3, 0x3, 0x3],
        kind: Kind::ReceptionL,
        ground: Ground::Radio,
    },
    Rule {
        map: "RadioTower5F",
        tileset: "radio_tower",
        anchor: None,
        width: 4,
        height: 2,
        fingerprint: 0x593a9c75b4606fb3,
        rows: &[0xf, 0xf],
        kind: Kind::CounterExtension,
        ground: Ground::Radio,
    },
];
