// Complete source identities, not copied artwork or map data.
const RULES: &[Rule] = &[
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x7834c97144120621,
        rows: &[0xf, 0xf, 0xf, 0xf],
        kind: Kind::SquareTable,
        ground: Ground::Checker,
    },
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x9a1b8b89b1f53a11,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "MrPokemonsHouse",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x3f1913aa74c99dc9,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x93d5fc0ea11b0bb0,
        rows: &[0xf, 0xf, 0xf, 0x0],
        kind: Kind::SideDesk,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 8,
        height: 8,
        fingerprint: 0x3eb5a384e0ed126c,
        rows: &[0x0, 0x0, 0xfc, 0xfc, 0xfc, 0xfc, 0x0, 0x0],
        kind: Kind::MeetingTable,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x85272ccc3eea1351,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x205d46601baa7035,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x4c4bdc770ce112f9,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x93913e65d812054d,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x9a1b8b89b1f53a11,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "PowerPlant",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x3f1913aa74c99dc9,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "RuinsOfAlphResearchCenter",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x93d5fc0ea11b0bb0,
        rows: &[0xf, 0xf, 0xf, 0x0],
        kind: Kind::SideDesk,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 8,
        height: 8,
        fingerprint: 0x3eb5a384e0ed126c,
        rows: &[0x0, 0x0, 0xfc, 0xfc, 0xfc, 0xfc, 0x0, 0x0],
        kind: Kind::MeetingTable,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x85272ccc3eea1351,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x205d46601baa7035,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x4c4bdc770ce112f9,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x93913e65d812054d,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "SilphCo1F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x0dccfecca702bb49,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 4,
        height: 4,
        fingerprint: 0x93d5fc0ea11b0bb0,
        rows: &[0xf, 0xf, 0xf, 0x0],
        kind: Kind::SideDesk,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 8,
        height: 8,
        fingerprint: 0x3eb5a384e0ed126c,
        rows: &[0x0, 0x0, 0xfc, 0xfc, 0xfc, 0xfc, 0x0, 0x0],
        kind: Kind::MeetingTable,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x85272ccc3eea1351,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x205d46601baa7035,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x4c4bdc770ce112f9,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
    Rule {
        map: "TeamRocketBaseB3F",
        tileset: "facility",
        anchor: None,
        width: 2,
        height: 2,
        fingerprint: 0x93913e65d812054d,
        rows: &[0x3, 0x3],
        kind: Kind::Chair,
        ground: Ground::Checker,
    },
];
