#!/usr/bin/env python3
"""One-time lossless migration from legacy payloads to raw JSON and native Blender assets.

No network or geometry generation. Run --check to verify without writing. All
inputs are validated before mutation; preexisting differing binaries are refused.
Legacy base64 decoding exists only here to recover the already-authored bytes.
"""
from pathlib import Path
import argparse
import base64
import gzip
import hashlib
import io
import json
import re
import zlib
from model_asset_storage import MAX_MODEL_BYTES, store_model_bytes, validate_model_bytes
from johto_art_sources import REQUIRED_SOURCES
GZIP_FORMAT = 'geothite-model-gzip-file-v1'

OLD_CHUNKS = 'geothite-model-text-chunks-v1'
OLD_GZIP = 'geothite-model-gzip-v1'

def digest(data):
    return hashlib.sha256(data).hexdigest()

def checked(data, record, size='bytes', sha='sha256'):
    if type(record[size]) is not int or len(data) != record[size] or digest(data) != record[sha]:
        raise ValueError('stored byte identity differs')
    return data

def local_path(root, relative):
    path = root / relative
    if not path.resolve().is_relative_to(root.resolve()):
        raise ValueError('asset path escapes directory')
    return path

def inflate(payload, size):
    if type(size) is not int or not 0 < size <= MAX_MODEL_BYTES:
        raise ValueError('invalid decoded model size')
    decoder = zlib.decompressobj(16 + zlib.MAX_WBITS)
    raw = decoder.decompress(payload, size + 1)
    if not decoder.eof or decoder.unused_data or decoder.unconsumed_tail or len(raw) != size:
        raise ValueError('invalid model gzip boundary or size')
    raw.decode('utf-8')
    return raw

def legacy_model(path):
    raw = path.read_bytes()
    value = json.loads(raw)
    removed = []
    if value.get('storage') == OLD_CHUNKS:
        if set(value) != {'storage', 'bytes', 'sha256', 'chunks'} or not value['chunks']:
            raise ValueError('invalid legacy model descriptor')
        parts = []
        for index, entry in enumerate(value['chunks']):
            if entry['path'] != f'{path.name}.chunks/{index:03}.txt' or set(entry) != {'path','bytes','sha256'} or not 0 < entry['bytes'] <= 350000:
                raise ValueError('unsafe or invalid legacy model chunk')
            part = local_path(path.parent, entry['path'])
            payload = checked(part.read_bytes(), entry);payload.decode('utf-8')
            parts.append(payload);removed.append(part)
        wrapper = Path(str(path) + '.include.rs')
        expected = '// Generated by tools/model_asset_storage.py; exact original JSON bytes.\nconcat!(\n' + ''.join(f'    include_str!("{e["path"]}"),\n' for e in value['chunks']) + ')\n'
        if wrapper.read_text() != expected:
            raise ValueError('legacy Rust wrapper differs from model descriptor')
        removed.append(wrapper)
        raw = checked(b''.join(parts), value);value = json.loads(raw)
    if value.get('storage') == OLD_GZIP:
        if set(value) != {'storage','bytes','sha256','data'}:
            raise ValueError('invalid legacy gzip envelope')
        compressed = base64.b64decode(value['data'], validate=True)
        raw = checked(inflate(compressed, value['bytes']), value)
    elif value.get('storage') == GZIP_FORMAT:
        if set(value) != {'storage','bytes','sha256','gzip_bytes','gzip_sha256'}:
            raise ValueError('invalid legacy gzip file descriptor')
        binary = Path(str(path) + '.gz')
        compressed = checked(binary.read_bytes(), value, 'gzip_bytes', 'gzip_sha256')
        raw = checked(inflate(compressed, value['bytes']), value)
        removed.append(binary)
    elif 'storage' in value:
        raise ValueError('unsupported model format')
    else:
        compressed = None
    validate_model_bytes(raw)
    return raw, compressed, removed

def migrate(root, check=False):
    root = Path(root).resolve()
    source_dir = root / 'art/johto/source'
    manifest_path = source_dir / 'manifest.json'
    manifest = json.loads(manifest_path.read_text())
    if manifest['format_version'] not in (3,4):
        raise ValueError('unsupported editable source manifest')
    sources = [];source_chunks = set()
    names = [entry['file'] for entry in manifest['sources']]
    if len(set(names)) != len(names) or not REQUIRED_SOURCES.issubset(names):
        raise ValueError('duplicate or missing editable source')
    for entry in manifest['sources']:
        name = Path(entry['file'])
        if name.name != entry['file'] or name.suffix != '.blend' or entry['encoding'] != 'gzip-blend':
            raise ValueError('invalid source filename or encoding')
        path = local_path(source_dir, entry['file'])
        if manifest['format_version'] == 3:
            parts = []
            for index, part in enumerate(entry['chunks']):
                if part['file'] != f'chunks/{entry["file"]}.{index:03}.b64' or part['encoding'] != 'base64' or not 0 < part['bytes'] <= 65536:
                    raise ValueError('unsafe or invalid source chunk')
                chunk_path = local_path(source_dir, part['file'])
                parts.append(checked(base64.b64decode(chunk_path.read_bytes(), validate=True), part))
                source_chunks.add(chunk_path)
            payload = checked(b''.join(parts), entry)
        else:
            payload = checked(path.read_bytes(), entry)
        raw = checked(gzip.decompress(payload), entry, 'uncompressed_bytes', 'uncompressed_sha256')
        if not raw.startswith(b'BLENDER'):
            raise ValueError('invalid Blender header')
        if path.exists() and path.read_bytes() != payload:
            raise ValueError(f'refusing to overwrite locally edited source: {path}')
        sources.append((path, payload, {k:v for k,v in entry.items() if k != 'chunks'}))
    actual_chunks = set((source_dir/'chunks').glob('*'))
    if actual_chunks != source_chunks:
        raise ValueError('orphan or missing editable source chunks')
    model_dir = root/'crates/crystal-voxel-view/models'
    models = [];model_chunks = set();wrappers = set()
    for path in sorted(model_dir.rglob('*.json')):
        if path.is_symlink():
            raise ValueError('symlinked canonical model cannot be migrated')
        raw, compressed, removed = legacy_model(path)
        binary = Path(str(path) + '.gz')
        if binary.exists() and binary not in removed:
            raise ValueError(f'refusing to remove unclaimed binary model: {binary}')
        models.append((path, raw, compressed, removed))
        model_chunks.update(p for p in removed if p.suffix == '.txt')
        wrappers.update(p for p in removed if p.suffix == '.rs')
    actual_model_chunks = {p for d in model_dir.rglob('*.json.chunks') for p in d.iterdir()}
    if actual_model_chunks != model_chunks or set(model_dir.rglob('*.json.include.rs')) != wrappers:
        raise ValueError('orphan or missing model chunks/wrappers')
    actual_gzip = set(model_dir.rglob('*.json.gz'))
    claimed_gzip = {p for _,_,_,removed in models for p in removed if p.suffix == '.gz'}
    if actual_gzip != claimed_gzip:
        raise ValueError('orphan or missing legacy binary models')
    report = {'sources':len(sources),'source_bytes':sum(len(p) for _,p,_ in sources),
              'models':len(models),'runtime_decoded_bytes':sum(len(r) for _,r,_,_ in models),
              'largest_source':max(({'file':p.name,'bytes':len(b)}for p,b,_ in sources),key=lambda x:x['bytes']),
              'largest_model':max(({'file':str(p.relative_to(root)),'bytes':len(b)}for p,b,_,_ in models),key=lambda x:x['bytes']),
              'changed_paths':sorted({str(p.relative_to(root)) for p in [manifest_path, *source_chunks, *(p for p,_,_ in sources), *(p for p,_,_,_ in models), *(old for _,_,_,removed in models for old in removed)]}),
              'source_identities':[entry for _,_,entry in sources],
              'model_identities':[{'file':str(p.relative_to(root)),'bytes':len(raw),'sha256':digest(raw)}for p,raw,z,_ in models]}
    if check:
        return report
    for path,payload,_ in sources:
        path.write_bytes(payload)
    for path,raw,compressed,removed in models:
        store_model_bytes(path,raw)
        for obsolete in removed:
            obsolete.unlink()
        directory=Path(str(path)+'.chunks')
        if directory.exists():directory.rmdir()
    manifest['format_version']=4
    manifest['sources']=[entry for _,_,entry in sources]
    manifest_path.write_text(json.dumps(manifest,indent=2)+'\n')
    for path in source_chunks:path.unlink()
    if (source_dir/'chunks').exists():(source_dir/'chunks').rmdir()
    # Verification is independent of the legacy reader after all mutations.
    from johto_art_sources import load_sources
    from model_asset_storage import validate_storage
    assert len(list(load_sources(source_dir))) == len(sources)
    assert len(validate_storage(model_dir)) == len(models)
    return report

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root',type=Path,default=Path(__file__).resolve().parent.parent)
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--report',type=Path,help='optional verification report, keep outside tracked source')
    args=parser.parse_args()
    report=migrate(args.root,args.check)
    if args.report:args.report.write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps({k:v for k,v in report.items() if not k.endswith('_identities') and k != 'changed_paths'},indent=2))
