#!/usr/bin/env python3
"""Lossless, bounded text storage for large original model JSON documents.

Rust concat!/include_str! joins chunks at compile time, without a runtime decoder.
The small canonical JSON path is a verifiable storage descriptor. Authoring tools
should use read_model_bytes/read_model_json rather than reading a descriptor as art.
"""
from pathlib import Path, PurePosixPath
import argparse
import base64
import gzip
import io
import hashlib
import json
import re

FORMAT = 'geothite-model-text-chunks-v1'
GZIP_FORMAT = 'geothite-model-gzip-v1'
MAX_MODEL_BYTES = 16 * 1024 * 1024
MAX_CHUNK_BYTES = 350_000

def sha(data):
    return hashlib.sha256(data).hexdigest()

def _descriptor(path):
    value = json.loads(Path(path).read_bytes())
    return value if isinstance(value, dict) and value.get('storage') == FORMAT else None

def _chunk_paths(path, descriptor):
    path = Path(path)
    if set(descriptor) != {'storage', 'bytes', 'sha256', 'chunks'}:
        raise ValueError(f'{path}: unexpected descriptor fields')
    if type(descriptor['bytes']) is not int or not 0 < descriptor['bytes'] <= MAX_MODEL_BYTES * 2:
        raise ValueError('invalid model byte count')
    if not re.fullmatch('[0-9a-f]{64}', descriptor['sha256']):
        raise ValueError('invalid model digest')
    chunks = descriptor['chunks']
    if not isinstance(chunks, list) or not chunks:
        raise ValueError('empty chunk list')
    result = []
    for index, entry in enumerate(chunks):
        if not isinstance(entry, dict) or set(entry) != {'path', 'bytes', 'sha256'}:
            raise ValueError('invalid chunk fields')
        name = entry['path']
        expected = f'{path.name}.chunks/{index:03}.txt'
        # Exact ordinal paths prohibit traversal, alternate spellings and reuse.
        if not isinstance(name, str) or name != expected or PurePosixPath(name).is_absolute():
            raise ValueError('unsafe, duplicate or misordered model chunk path')
        candidate = path.parent / name
        if not candidate.resolve().is_relative_to(path.parent.resolve()):
            raise ValueError('model chunk escapes its asset directory')
        if type(entry['bytes']) is not int or not 0 < entry['bytes'] <= MAX_CHUNK_BYTES:
            raise ValueError('invalid chunk byte count')
        if not re.fullmatch('[0-9a-f]{64}', entry['sha256']):
            raise ValueError('invalid chunk digest')
        result.append(candidate)
    return result

def wrapper_text(path, descriptor):
    _chunk_paths(path, descriptor)
    return '// Generated by tools/model_asset_storage.py; exact original JSON bytes.\nconcat!(\n' + ''.join(
        f'    include_str!("{entry["path"]}"),\n' for entry in descriptor['chunks']) + ')\n'

def wrapper_path(path):
    return Path(str(path) + '.include.rs')

def read_stored_bytes(path):
    path = Path(path)
    raw = path.read_bytes()
    value = json.loads(raw)
    if not isinstance(value, dict) or value.get('storage') != FORMAT:
        return raw
    chunks = []
    for candidate, entry in zip(_chunk_paths(path, value), value['chunks']):
        data = candidate.read_bytes()
        data.decode('utf-8')
        if len(data) != entry['bytes'] or sha(data) != entry['sha256']:
            raise ValueError(f'corrupt model chunk: {candidate}')
        chunks.append(data)
    joined = b''.join(chunks)
    if len(joined) != value['bytes'] or sha(joined) != value['sha256']:
        raise ValueError(f'model reconstruction mismatch: {path}')
    # The exact bytes compiled by Rust must be the same checked payload.
    if wrapper_path(path).read_text() != wrapper_text(path, value):
        raise ValueError(f'Rust model include differs from storage descriptor: {path}')
    return joined

def decode_model_bytes(raw):
    value = json.loads(raw)
    if not isinstance(value, dict) or 'storage' not in value:
        return raw
    if value.get('storage') != GZIP_FORMAT or set(value) != {'storage', 'bytes', 'sha256', 'data'}:
        raise ValueError('unsupported or malformed compressed model document')
    if type(value['bytes']) is not int or not 0 < value['bytes'] <= MAX_MODEL_BYTES:
        raise ValueError('invalid decoded model byte limit')
    if not isinstance(value['sha256'], str) or not re.fullmatch('[0-9a-f]{64}', value['sha256']):
        raise ValueError('invalid decoded model digest')
    if not isinstance(value['data'], str) or len(value['data']) > MAX_MODEL_BYTES * 2:
        raise ValueError('invalid compressed model payload')
    compressed = base64.b64decode(value['data'], validate=True)
    with gzip.GzipFile(fileobj=io.BytesIO(compressed)) as stream:
        decoded = stream.read(value['bytes'] + 1)
    if len(decoded) != value['bytes'] or sha(decoded) != value['sha256']:
        raise ValueError('decoded model identity mismatch')
    decoded.decode('utf-8')
    return decoded

def read_model_bytes(path):
    return decode_model_bytes(read_stored_bytes(path))

def read_model_text(path):
    return read_model_bytes(path).decode('utf-8')

def read_model_json(path):
    return json.loads(read_model_bytes(path))

def pack_model(path, chunk_bytes=MAX_CHUNK_BYTES):
    path = Path(path)
    if not 1 <= chunk_bytes <= MAX_CHUNK_BYTES:
        raise ValueError('chunk size exceeds the bounded storage contract')
    original = read_model_bytes(path)
    if len(original) <= chunk_bytes and _descriptor(path) is None:
        return False
    payload = json.loads(original)
    if not isinstance(payload, dict) or 'storage' in payload:
        raise ValueError('expected a canonical model document')
    return _write_chunked(path, original, chunk_bytes)

def _write_chunked(path, original, chunk_bytes):
    descriptor = {'storage': FORMAT, 'bytes': len(original), 'sha256': sha(original), 'chunks': []}
    start = 0
    directory = Path(str(path) + '.chunks')
    directory.mkdir(exist_ok=True)
    while start < len(original):
        end = min(start + chunk_bytes, len(original))
        while end < len(original) and original[end] & 0xc0 == 0x80:
            end -= 1
        if end == start:
            raise ValueError('chunk cannot hold one UTF-8 code point')
        data = original[start:end]
        data.decode('utf-8')
        name = f'{len(descriptor["chunks"]):03}.txt'
        (directory / name).write_bytes(data)
        descriptor['chunks'].append({'path': f'{directory.name}/{name}', 'bytes': len(data), 'sha256': sha(data)})
        start = end
    expected = {Path(entry['path']).name for entry in descriptor['chunks']}
    for old in directory.glob('*.txt'):
        if old.name not in expected:
            old.unlink()  # Only superseded generated chunks of this exact asset.
    wrapper_path(path).write_text(wrapper_text(path, descriptor))
    path.write_text(json.dumps(descriptor, indent=2) + '\n')
    if read_stored_bytes(path) != original:
        raise ValueError('storage changed canonical bytes')
    return True

def compress_model(path, chunk_bytes=MAX_CHUNK_BYTES):
    path = Path(path)
    original = read_model_bytes(path)
    if not 0 < len(original) <= MAX_MODEL_BYTES:
        raise ValueError('model exceeds bounded decode limit')
    buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=buffer, mode='wb', filename='', compresslevel=6, mtime=0) as stream:
        stream.write(original)
    packed = json.dumps({'storage': GZIP_FORMAT, 'bytes': len(original), 'sha256': sha(original),
                         'data': base64.b64encode(buffer.getvalue()).decode('ascii')}, separators=(',', ':')).encode()+b'\n'
    if len(packed) > chunk_bytes:
        _write_chunked(path, packed, chunk_bytes)
    else:
        path.write_bytes(packed)
        wrapper_path(path).unlink(missing_ok=True)
        directory = Path(str(path)+'.chunks')
        if directory.exists():
            for part in directory.glob('*.txt'): part.unlink()
            directory.rmdir()
    if read_model_bytes(path) != original:
        raise ValueError('compression changed canonical bytes')
    return len(original), len(packed)

def validate_storage(root):
    root = Path(root)
    descriptors = []
    used = set()
    for path in sorted(root.rglob('*.json')):
        descriptor = _descriptor(path)
        if descriptor is None:
            read_model_json(path)
            continue
        read_model_json(path)
        for chunk in _chunk_paths(path, descriptor):
            resolved = chunk.resolve()
            if resolved in used:
                raise ValueError('model chunk reused by multiple assets')
            used.add(resolved)
        descriptors.append(path)
    actual = {p.resolve() for directory in root.rglob('*.json.chunks') for p in directory.glob('*.txt')}
    if actual != used:
        raise ValueError('orphan or missing model text chunks')
    wrappers = {p.resolve() for p in root.rglob('*.json.include.rs')}
    if wrappers != {wrapper_path(p).resolve() for p in descriptors}:
        raise ValueError('orphan or missing Rust model wrappers')
    return descriptors

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='action', required=True)
    pack = sub.add_parser('pack'); pack.add_argument('paths', nargs='+', type=Path)
    compress = sub.add_parser('compress'); compress.add_argument('paths', nargs='+', type=Path)
    verify = sub.add_parser('validate'); verify.add_argument('root', type=Path)
    unpack = sub.add_parser('reconstruct'); unpack.add_argument('path', type=Path); unpack.add_argument('output', type=Path)
    args = parser.parse_args()
    if args.action == 'pack':
        for path in args.paths:
            pack_model(path)
            print(f'validated {path}')
    elif args.action == 'compress':
        for path in args.paths:
            before, after = compress_model(path)
            print(f'{path}: {before} -> {after} bytes')
    elif args.action == 'validate':
        print(f'Validated {len(validate_storage(args.root))} lossless chunked model documents')
    else:
        if args.output.exists():
            raise ValueError('refusing to overwrite an existing reconstructed file')
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(read_model_bytes(args.path))

if __name__ == '__main__':
    main()
