[package]
name = "crystal-assets"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
ciborium.workspace = true
crystal-core = { path = "../crystal-core" }
flate2 = "1.1"
serde.workspace = true
serde_path_to_error = "0.1"
serde_json.workspace = true
sha2.workspace = true

[features]
test-fixtures = ["crystal-core/test-fixtures"]

[dev-dependencies]
crystal-core = { path = "../crystal-core", features = ["test-fixtures"] }
